import { createFileRoute, Link, notFound } from "@tanstack/react-router";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { getReportBySlug } from "@/lib/research.functions";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { ExternalLink, Telescope } from "lucide-react";
import { formatDistanceToNow } from "date-fns";

type Source = { index: number; title: string; url: string };

export const Route = createFileRoute("/r/$slug")({
  loader: async ({ params }) => {
    const report = await getReportBySlug({ data: { slug: params.slug } });
    if (!report) throw notFound();
    return { report };
  },
  head: ({ loaderData }) => ({
    meta: [
      { title: loaderData?.report?.query ? `${loaderData.report.query} — Lumen Research` : "Shared report — Lumen Research" },
      { name: "description", content: "A shared research report generated by Lumen Research." },
    ],
  }),
  notFoundComponent: () => (
    <main className="mx-auto max-w-3xl px-4 py-20 text-center">
      <p className="text-muted-foreground">This shared report is not available.</p>
      <Button asChild variant="link" className="mt-4">
        <Link to="/">Go home</Link>
      </Button>
    </main>
  ),
  errorComponent: ({ error }) => (
    <main className="mx-auto max-w-3xl px-4 py-20 text-center">
      <p className="text-destructive">Failed to load report.</p>
      <p className="mt-2 text-xs text-muted-foreground">{error.message}</p>
    </main>
  ),
  component: SharedReportPage,
});

function SharedReportPage() {
  const { report } = Route.useLoaderData();
  const sources = (report.sources as Source[] | null) ?? [];

  return (
    <div className="min-h-screen bg-background">
      <header className="border-b border-border">
        <div className="mx-auto flex h-14 max-w-3xl items-center justify-between px-4">
          <Link to="/" className="flex items-center gap-2 font-semibold">
            <Telescope className="h-5 w-5 text-primary" />
            <span>Lumen Research</span>
          </Link>
          <Button asChild size="sm">
            <Link to="/signup">Create your own</Link>
          </Button>
        </div>
      </header>

      <main className="mx-auto max-w-3xl px-4 py-10">
        <h1 className="text-2xl font-bold tracking-tight text-foreground">{report.query}</h1>
        <p className="mt-2 text-xs text-muted-foreground">
          Shared · {formatDistanceToNow(new Date(report.created_at), { addSuffix: true })}
        </p>

        {report.content && (
          <article className="prose prose-neutral dark:prose-invert mt-8 max-w-none rounded-xl border border-border bg-card p-8 [&_a]:text-primary [&_h1]:mt-0 [&_h1]:text-3xl [&_h1]:font-bold [&_h2]:mt-8 [&_h2]:text-xl [&_h2]:font-semibold [&_h3]:mt-6 [&_h3]:text-lg [&_h3]:font-semibold [&_li]:my-1 [&_li]:text-foreground [&_p]:my-3 [&_p]:leading-7 [&_p]:text-foreground [&_strong]:text-foreground [&_ul]:my-3 [&_ul]:list-disc [&_ul]:pl-6 [&_ol]:my-3 [&_ol]:list-decimal [&_ol]:pl-6">
            <ReactMarkdown remarkPlugins={[remarkGfm]}>{report.content}</ReactMarkdown>
          </article>
        )}

        {sources.length > 0 && (
          <section className="mt-8 rounded-xl border border-border bg-card p-6">
            <h2 className="flex items-center gap-2 font-semibold text-card-foreground">
              <Badge variant="secondary">{sources.length}</Badge> Sources
            </h2>
            <ol className="mt-4 space-y-2 text-sm">
              {sources.map((s) => (
                <li key={s.url} className="flex gap-2">
                  <span className="shrink-0 text-muted-foreground">[{s.index}]</span>
                  <a
                    href={s.url}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="inline-flex items-start gap-1 text-foreground hover:text-primary hover:underline"
                  >
                    <span>{s.title}</span>
                    <ExternalLink className="mt-0.5 h-3 w-3 shrink-0" />
                  </a>
                </li>
              ))}
            </ol>
          </section>
        )}

        <div className="mt-12 rounded-xl border border-border bg-card p-6 text-center">
          <p className="text-sm font-medium text-card-foreground">Want reports like this for your own questions?</p>
          <p className="mt-1 text-sm text-muted-foreground">Lumen runs deep, cited research in minutes.</p>
          <Button asChild className="mt-4">
            <Link to="/signup">Try Lumen free</Link>
          </Button>
        </div>
      </main>
    </div>
  );
}
